version: '2'

services:
  mfw_traffic:
    image: ${IMAGE}
    entrypoint: bash -c '/entrypoint.sh'
    networks:
      mfw_net:
    volumes:
      - ${MFW_LOG_DIR}:/logs/
    #  - ./pytraffic.py:/traffic/pytraffic.py
      - ./url.txt:/traffic_gen/url.txt
      - ./entrypoint.sh:/entrypoint.sh

networks:
  # network for mfw devices 192.168.1.0/24
  mfw_net:
    driver: macvlan
    driver_opts:
      parent: ${MFW_NIC}
    ipam:
      config:
      #- subnet: 10.11.12.0/24
      #  gateway: 10.11.12.1
      #  ip_range: 10.11.12.200/26
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
        ip_range: 192.168.1.200/26
