version: '2'

services:
  mfw_traffic:
    image: container-registry.untangle.com/traffic_gen:latest
    entrypoint: bash -c '/traffic_gen/entrypoint.sh'
    networks:
      mfw_net:
    volumes:
      - ${LOG_DIR}:/logs/

networks:
  # network for mfw devices 192.168.1.0/24
  mfw_net:
    driver: macvlan
    driver_opts:
      parent: ${MFW_NIC}
    ipam:
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
        ip_range: 192.168.1.200/26